# Generated by Django 4.1.2 on 2023-01-25 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dt_of_join',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
